import React from 'react';
import styleAdmin from '../styles/baseAdmin.module.css';
import Head from 'next/head';
import Link from 'next/link'


export default function BaseAdmin(props) {
    return (
        <div>
            <Head>
                <title>Admin Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins" />
            </Head>
            <main className={styleAdmin.mainContainerAdmin}>
                <nav className={styleAdmin.sideNavbar}>
                    <h3>Message</h3>
                    <h3><Link href="/admin-secret/admins/listBlog">Blog</Link></h3>
                    <h3>Works</h3>
                </nav>
                <div>
                    <nav className={styleAdmin.topNavbar}>

                    </nav>
                    <div className={styleAdmin.contentAdminContainer}>
                        {
                            props.content
                        }
                    </div>
                </div>
            </main>
            
        </div>
    )
}